# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_activation_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activated',
            new_name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activation_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
