# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pet_type', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=20)),
            ],
        ),
    ]
