# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='colour',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Calico', 'Calico'), ('Chocolate', 'Chocolate'), ('Cinnamon', 'Cinnamon'), ('Cream', 'Cream'), ('Fawn', 'Fawn'), ('Ginger', 'Ginger'), ('Grey', 'Grey'), ('Lilac', 'Lilac'), ('Red', 'Red'), ('Black', 'Black'), ('Tabby', 'Tabby'), ('Tortoiseshell', 'Tortoiseshell'), ('White', 'White')], max_length=20, null=True),
        ),
    ]
