# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_lostpet_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Big', 'Big'), ('Very Big!', 'Very Big!')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='pet_type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=20, null=True),
        ),
    ]
