# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20170820_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='collar',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='desexed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='microchipped',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='microchipped_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='missing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
