# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20170820_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
