# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0012_remove_lostpet_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostpet',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='lostpet',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
