# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_auto_20170905_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Rabbit', 'Rabbit'), ('Pig', 'Pig'), ('Bird', 'Bird'), ('Ferret', 'Ferret'), ('Horse', 'Horse'), ('Sheep', 'Sheep'), ('Turtle', 'Turtle')], max_length=20, null=True),
        ),
    ]
