# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_pet_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(null=True, upload_to='pets/'),
        ),
    ]
